### Aqui comienza el estudio del perceptron basico. utilizando el libro *Neural Networks from Scratch in Python*


In [1]:
# Aqui lo que vemos es una neurona con tres entradas, y por ende tiene 
# tres pesos y un sesgo
inputs = [1, 2, 3] #entradas a mi red neuronal
weights = [0.2, 0.8, -0.5] #pesos
bias = 2 #sesgo

output = (inputs[0]*weights[0] + #salida    #salida = entrada*peso+sesgo   (y = xm+b)
inputs[1]*weights[1] +           #para este caso como son tres entradas, por eso se hace tres vecss la operacion y al 
inputs[2]*weights[2] + bias)        #final se suma el sesgo

print(f"salida de la neurona #1, {output}") #impresion de salida

salida de la neurona #1, 2.3


### Aqui agregamos otra entrada y otro peso, y utilizamos la amnera mas comun de sumar y multiplicar.

In [7]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
output = (inputs[0]*weights[0] +        #salida    #salida = entrada*peso+sesgo   (y = xm+b
inputs[1]*weights[1] +                  #para este caso como son tres entradas, por eso se hace cuatro vecss la operacion y al 
inputs[2]*weights[2] +                   #final se suma el sesgo
inputs[3]*weights[3] + bias)
print(f"salida de la neurona #2, {output}") #impresion de salida


salida de la neurona #2, 4.8


### Tres neuronas, una capa
##### Esta es haciendolo de la forma mas basica, multiplicando y sumando uno por uno

In [9]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5
outputs = [
# Neuron 1:
inputs[0]*weights1[0] +
inputs[1]*weights1[1] +
inputs[2]*weights1[2] +
inputs[3]*weights1[3] + bias1,
# Neuron 2:
inputs[0]*weights2[0] +
inputs[1]*weights2[1] +
inputs[2]*weights2[2] +
inputs[3]*weights2[3] + bias2,
# Neuron 3:
inputs[0]*weights3[0] +
inputs[1]*weights3[1] +
inputs[2]*weights3[2] +
inputs[3]*weights3[3] + bias3]
print(f"Salida de las 3 neuronas {outputs}")

Salida de las 3 neuronas [4.8, 1.21, 2.385]


### a pesar de lo facil que es hacer esto, cuando se habla de cientos de neuronas es mucho mas dificil programar todo, es por ello que a continucion se presenta el proceso anterior, pero utilizando un ciclo for, en el cual solo tendremos que declarar los vectores de entradas, pesos y sesgos.


In [12]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
# Output of current layer
layer_outputs = []
# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    print(f"De esta concatenacion se encarga \"zip\",pesos {neuron_weights}, bias {neuron_bias}")
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron’s output variable
        neuron_output += n_input*weight
    # Add bias
    neuron_output += neuron_bias
    # Put neuron’s result to the layer’s output list
    layer_outputs.append(neuron_output)
    print("Aqui termina la vuelta de los for")
print(f"salidas {layer_outputs}")

De esta concatenacion se encarga "zip",pesos [0.2, 0.8, -0.5, 1], bias 2
Aqui termina la vuelta de los for
De esta concatenacion se encarga "zip",pesos [0.5, -0.91, 0.26, -0.5], bias 3
Aqui termina la vuelta de los for
De esta concatenacion se encarga "zip",pesos [-0.26, -0.27, 0.17, 0.87], bias 0.5
Aqui termina la vuelta de los for
salidas [4.8, 1.21, 2.385]


### Explicacion de lista de listas

In [15]:
l = [1,5,6,2]
#A list of lists:
lol = [[1,5,6,2],
[3,2,1,3]]
#A list of lists of lists!
lolol = [[[1,5,6,2], 
          [3,2,1,3]],
          [[5,2,1,2],
           [6,4,8,4]],
           [[2,8,5,3],
            [1,1,9,4]]]

### Producto punto
#### El producto punto se desarrolla de la siguiente manera,al tener dos vectores multiplicamos los mismos indices de cada arreglo.

In [17]:
a = [1,2,3]
b = [2,3,4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

20


### Una sola neurona con NumPy
#### Como podremos observar np.dot se encraga de hacer lo que normalmente hacemos para el producto punto y se encarga de realizarlo para todos los valores de las listas, y al final se suma el Bias

In [18]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


### Numpy y tres neuronas
#### una capa de neuronas con numpy

#### Aqui numpy se encarga de realizar la multiplicacion de cada  entrada por su peso y al final le suma el bias, es lo que hicimos anteriormente con el for, pero ahora con menos lineas de codigo

In [2]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
[0.5, -0.91, 0.26, -0.5],
[-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)


[4.8   1.21  2.385]


### Un conjunto de datos
#### An example of a batch of data could look like:


In [21]:
# Shape = (8, 4)
# type = 2D array, matriz
inputs = [[1, 2, 3, 2.5],
          [2, 5, -1, 2],
          [1, 2, 3, 2.5],
          [1, 2, 3, 2.5],
          [2, 5, -1, 2],
          [1, 2, 3, 2.5],
          [2, 5, -1, 2],
          [1, 2, 3, 2.5]]

### Producto de matrices
### Una vez visto el producto punto, vamos a ver lo que el producto de matrices

##### El producto matricial es una operación en la que tenemos 2 matrices, y estamos realizando productos escalar de todas las combinaciones de filas de la primera matriz y las columnas de la 2ª matriz, dando como resultado una matriz de esos productos de puntos atómicos

##### En matemáticas, podemos tener algo llamado vector columna y vector fila, que explicaremos mejor en breve. Son vectores, pero representados como matrices con una de las dimensiones que tiene un tamaño de 1

para poder multiplicar vectores debemos tenerlos como vectores fila y vectores columna

### Transposicion de la matriz producto
Con NumPy y con 3 valores, lo definiríamos como:

In [3]:

np.array([[1, 2, 3]])

array([[1, 2, 3]])

Tenga en cuenta el uso de corchetes dobles aquí. Para transformar una lista en una matriz que contenga una sola fila (realizar una operación equivalente de convertir un vector en un vector fila), podemos ponerlo en una lista y crear una matriz numpy

In [4]:
a = [1, 2, 3]
np.array([a])

array([[1, 2, 3]])

Una vez más, tenga en cuenta que encerramos a entre paréntesis antes de convertir en una matriz en este caso. O podemos convertirlo en una matriz 1D y expandir las dimensiones usando una de las habilidades de NumPy:

In [5]:
a = [1, 2, 3]
np.expand_dims(np.array(a), axis=0)
#Donde np.expand_dims() añade una nueva dimensión en el índice del eje. Un vector 
#columna es una matriz donde el tamaño de la segunda dimensión es igual a 1, en otras
#palabras, es una matriz de forma (n, 1)


array([[1, 2, 3]])

In [6]:
# con codigo numpy:
import numpy as np
a = [1, 2, 3]
b = [2, 3, 4]
a = np.array([a])
b = np.array([b]).T
np.dot(a, b)

array([[20]])

### Una capa de neuronas y un lote de datos con NumPy